
services:
  text-generation-api:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./models:/app/models  
    environment:
      - ENVIRONMENT=development
      - MODEL_PATH=/app/models
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s